FROM python:3.11

WORKDIR /app

# Copy moke and requirements.txt to the work directory
COPY moke.py ./
COPY requirements.txt ./

# Install any needed dependencies specified in requirements.txt
RUN pip install -r requirements.txt

# Run app.py when the container launches
CMD ["python", "moke.py"]