FOGV_CMD_REQUEST_DEPLOY = 'REQUEST_DEPLOY'

FOGV_STATUS_CLOUD_DEPLOYED = 'DEPLOYED_IN_CLOUD'
FOGV_STATUS_RUNNING = 'RUNNING'
FOGV_STATUS_SHUTDOWN = 'SHUTDOWN'

FOGV_STATUS_RUN_IN_CLOUD = 'RUN_IN_CLOUD'
FOGV_STATUS_RUN_IN_LOCAL = 'RUN_IN_LOCAL'
