FROM python:3.11

WORKDIR /app
COPY analyzer ./analyzer
COPY master ./master
COPY fogverse ./fogverse
COPY crawler ./crawler
COPY mocking_bird ./mocking_bird
COPY jay_bird ./jay_bird
COPY requirements/analyzer.txt ./

RUN pip install -r analyzer.txt

CMD ["python","-m", "analyzer"]
