FROM python:3.11

WORKDIR /app
COPY master ./master
COPY fogverse ./fogverse
COPY requirements/master.txt ./
COPY --chmod=755 scripts/create_cpu_instance.sh scripts/create_cpu_instance.sh ./scripts

RUN pip install -r master.txt

CMD ["python","-m", "master"]
