FROM python:3.10

WORKDIR /app
COPY master ./master
COPY fogverse ./fogverse
COPY requirements/master.txt ./
COPY --chmod=755 scripts ./scripts

RUN pip install -r master.txt

CMD ["python","-m", "master"]
