FROM python:3.11

WORKDIR /app

COPY master ./master
COPY model ./model
COPY fogverse ./fogverse
COPY scripts ./scripts

COPY moke ./moke

COPY requirements/moke.txt ./
COPY requirements/master.txt ./

RUN pip install -r moke.txt
RUN pip install -r master.txt

CMD ["python", "-m", "moke"]