FROM python:3.11

WORKDIR /app
COPY crawler ./crawler
COPY fogverse ./fogverse
COPY master ./master
COPY data ./data
COPY requirements/crawler.txt ./
COPY scripts ./scripts

RUN pip install -r crawler.txt

CMD ["python","-m", "crawler"]
