FROM python:3.11

WORKDIR /app

COPY discord_bot ./discord_bot
COPY fogverse ./fogverse
COPY master ./master
COPY model ./model
COPY data ./data
COPY scripts ./scripts

COPY requirements/crawler.txt ./

RUN pip install -r crawler.txt

CMD ["python","-m", "discord_bot"]