FROM pytorch/pytorch:2.2.1-cuda12.1-cudnn8-runtime

WORKDIR /app
COPY analyzer ./analyzer
COPY master ./master
COPY fogverse ./fogverse
COPY model ./model
COPY requirements/analyzer.txt ./
COPY scripts ./scripts

RUN pip install -r analyzer.txt

CMD ["python","-m", "analyzer"]
