FROM python:3.11

WORKDIR /app
COPY client ./client
COPY fogverse ./fogverse
COPY master ./master
COPY model ./model
COPY requirements/client.txt ./
COPY scripts ./scripts

RUN pip install -r client.txt

CMD ["python","-m", "client"]